#
# Module manifest for module 'PsTimeTracking'
#
# Generated by: Jess Pomfret
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PsTimeTracking.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# ID used to uniquely identify this module
GUID = '30596af7-2bd8-4a23-856b-15d9b3adb589'

# Author of this module
Author = 'Jess Pomfret'

# Company or vendor of this module
CompanyName = 'Jess Pomfret'

# Copyright statement for this module
Copyright = '(c) Jess Pomfret. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module to make tracking time easier. Track time across clients and projects with interactive timers, manual entries, and daily summaries.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module
FunctionsToExport = @(
    'Add-PstClient'
    'Add-PstProject'
    'Add-PstTime'
    'Backup-PstDay'
    'Get-PstClient'
    'Get-PstDaySummary'
    'Get-PstProject'
    'Move-PstTime'
    'Open-PstConfig'
    'Open-PstDay'
    'Remove-PstClient'
    'Remove-PstProject'
    'Restore-PstDay'
    'Start-PstTimer'
    'Update-PstClient'
    'Update-PstProject'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{

    PSData = @{

        Prerelease = ''

        # Tags applied to this module for module discovery in online galleries.
        Tags = @('TimeTracking', 'Productivity', 'Timer', 'Time', 'PSEdition_Core', 'PSEdition_Desktop', 'Windows', 'Linux', 'MacOS')

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/jpomfret/PsTimeTracking'

        # Release notes for this version
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
